In [6]:
1 + 1

2

In [7]:
1+2

3

In [8]:
1*2

2

In [9]:
1-2

-1

In [10]:
1<<2

4

In [11]:
2<<2

8

In [12]:
1>>2

0

In [13]:
1 & 2

0

In [14]:
1 & 1

1

In [15]:
1 && 1

SyntaxError: invalid syntax (3280347098.py, line 1)

In [16]:
1 and 1

1

In [17]:
1 % 2

1

In [18]:
2 % 2

0

In [19]:
# haha

# 안녕하세요 파이썬을 시작해볼게요
## 하하ㅏ하하하ㅏ하하
### 한상빈 돼지
* 나이스

In [20]:
10 / 4

2.5

In [21]:
10 ** 2

100

In [22]:
(2+2)*3

12

In [23]:
2 + 2 * 3

8

In [24]:
1 > 2

False

In [25]:
2 > 2

False

In [26]:
2 >= 2

True

In [27]:
1 == 1

True

In [28]:
1 != 1

False

In [29]:
1 + 1
2 + 2

4

In [30]:
ㅆ겯 & ㄹ민ㄷ

NameError: name 'ᄊ겯' is not defined

In [31]:
True & False

False

In [32]:
a = 2

In [33]:
a

2

In [34]:
b = 3.3

In [35]:
b

3.3

In [36]:
cibal = "한생빈"
cibal

'한생빈'

In [37]:
a = .1
a

0.1

In [38]:
10.0 * 5.69123121231

56.9123121231

In [39]:
type(10)

int

In [42]:
a = 5.0

In [43]:
type(a)

float

In [44]:
1345141241e-5


13451.41241

In [45]:
bin(3)

'0b11'

In [46]:
0.1 + 0.2

0.30000000000000004

In [47]:
print("* " * 10)

* * * * * * * * * * 


In [48]:
print("ahaha")

ahaha


In [57]:
print("한상빈 \n     뛰.. \n      어.. \n       내.. \n        려.. \n         라..")

한상빈 
     뛰.. 
      어.. 
       내.. 
        려.. 
         라..


In [59]:
print('"haha"')

"haha"


In [65]:
print(
"""아니 한상빈 이 돼지는 무슨
맨날 먹기만 하냐 진짜 옆에서 기름 냄새 지린다.
어우 또 먹네 또 먹어"""
)

아니 한상빈 이 돼지는 무슨
맨날 먹기만 하냐 진짜 옆에서 기름 냄새 지린다.
어우 또 먹네 또 먹어


In [62]:
"Hello %s" % "최민재"


'Hello 최민재'

In [63]:
"Hello we are %s, %s, %s" % ("한상빈", "손원", "류지훈")

'Hello we are 한상빈, 손원, 류지훈'

In [66]:
"내 이름은 {}입니다.".format("최민재")

'내 이름은 최민재입니다.'

In [73]:
a = int(input("입력해주세요 : "))
if a == 3:
    print("haha")
else:
    print("nono")

입력해주세요 : 3
haha


In [75]:
def printNiceMan(name):
    print("nice man %s" % name)
    return "nice man"

In [76]:
print(printNiceMan("minjae"))

nice man minjae
nice man


In [77]:
f = lambda x : 2 * x

In [78]:
f(2)

4

In [79]:
for i in range(10):
    print("ahhahaha")

ahhahaha
ahhahaha
ahhahaha
ahhahaha
ahhahaha
ahhahaha
ahhahaha
ahhahaha
ahhahaha
ahhahaha


In [80]:
for i in range(10):
    print("*" * i)


*
**
***
****
*****
******
*******
********
*********


In [81]:
x = [1, 2, 3]
x

[1, 2, 3]

In [82]:
type(x)

list

In [87]:
#tuple
a = (1, 2, 3)
a
type(a)

tuple

In [88]:
x[1]

2

In [89]:
x[1] = 5

In [90]:
x[1]

5

In [91]:
a(2)

TypeError: 'tuple' object is not callable

In [92]:
a[2]

3

In [93]:
a[2] = 5

TypeError: 'tuple' object does not support item assignment

In [94]:
b = {"haha":1, "hoho":2}

In [95]:
b["haha"] = 5

In [96]:
b["haha"]

5

In [97]:
type(b)

dict

In [99]:
b

{'haha': 5, 'hoho': 2}

In [102]:
b["hoho"]

2

In [106]:
e=[[1, 20], [2, 20]]
e[0][1]

20

In [107]:
a = [{"aa":1, "bb":2}, {1:3, 2:4}]

In [108]:
a

[{'aa': 1, 'bb': 2}, {1: 3, 2: 4}]

In [109]:
len(a)

2

In [110]:
a = list(range(10))

In [111]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [112]:
c = list(range(10000, 1293410))
c

[10000,
 10001,
 10002,
 10003,
 10004,
 10005,
 10006,
 10007,
 10008,
 10009,
 10010,
 10011,
 10012,
 10013,
 10014,
 10015,
 10016,
 10017,
 10018,
 10019,
 10020,
 10021,
 10022,
 10023,
 10024,
 10025,
 10026,
 10027,
 10028,
 10029,
 10030,
 10031,
 10032,
 10033,
 10034,
 10035,
 10036,
 10037,
 10038,
 10039,
 10040,
 10041,
 10042,
 10043,
 10044,
 10045,
 10046,
 10047,
 10048,
 10049,
 10050,
 10051,
 10052,
 10053,
 10054,
 10055,
 10056,
 10057,
 10058,
 10059,
 10060,
 10061,
 10062,
 10063,
 10064,
 10065,
 10066,
 10067,
 10068,
 10069,
 10070,
 10071,
 10072,
 10073,
 10074,
 10075,
 10076,
 10077,
 10078,
 10079,
 10080,
 10081,
 10082,
 10083,
 10084,
 10085,
 10086,
 10087,
 10088,
 10089,
 10090,
 10091,
 10092,
 10093,
 10094,
 10095,
 10096,
 10097,
 10098,
 10099,
 10100,
 10101,
 10102,
 10103,
 10104,
 10105,
 10106,
 10107,
 10108,
 10109,
 10110,
 10111,
 10112,
 10113,
 10114,
 10115,
 10116,
 10117,
 10118,
 10119,
 10120,
 10121,
 10122,
 10123,
 10124,


In [113]:
d = list(range(1, 10, 2))

In [114]:
d

[1, 3, 5, 7, 9]

In [115]:
a.append(10)

In [116]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [117]:
a[3:5]

[3, 4]

In [119]:
a[-1]

10

In [120]:
for i in range(len(a)):
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [122]:
for i in a:
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [123]:
for i in [3, 4, 5, 6]:
    print(i)

3
4
5
6


In [124]:
x = {"a": 1, "b": 2}
x

{'a': 1, 'b': 2}

In [127]:
for i in x:
    print(i)

a
b


In [128]:
x.values()

dict_values([1, 2])

In [129]:
x.keys()

dict_keys(['a', 'b'])

## 넘파이
> 라이브러리를 만들어두는 것

In [130]:
import numpy as np

In [133]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [134]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [135]:
a + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [136]:
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [137]:
type(a)

numpy.ndarray

In [138]:
a.shape

(2, 3)

In [139]:
a.dtype

dtype('int64')