In [1]:
import numpy as np

In [2]:
 a= np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
b = a.T

In [6]:
b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [7]:
block_L = np.array([[0, 0, 0, 0],
                    [0, 1, 0, 0],
                    [0, 1, 1, 1],
                    [0, 0, 0, 0]])

In [8]:
block_L

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 1, 1],
       [0, 0, 0, 0]])

In [15]:
block_L.T

array([[0, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0]])

In [11]:
reverse_col = np.array([
    [0, 0, 0, -1],
    [0, 0, -1, 0],
    [0, -1, 0, 0],
    [-1, 0, 0, 0],
])

In [19]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

In [20]:
reverse_col

array([[ 0,  0,  0, -1],
       [ 0,  0, -1,  0],
       [ 0, -1,  0,  0],
       [-1,  0,  0,  0]])

In [21]:
b = a.T

In [22]:
b

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [23]:
block_L

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 1, 1],
       [0, 0, 0, 0]])

In [26]:
block_L = np.dot(block_L.T, reverse_col) * (-1)

In [27]:
block_L

array([[0, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0]])