In [1]:
import numpy as np

In [2]:
a = [1, 2, 3, 4]

In [3]:
a

[1, 2, 3, 4]

In [4]:
type(a)

list

In [5]:
ar = np.array([1, 2, 3])

In [6]:
ar

array([1, 2, 3])

In [7]:
type(ar)

numpy.ndarray

In [8]:
data = [0, 1, 2, 3, 4, 5, 6, 7 ,8, 9]

In [9]:
answer = []
for di in data:
    answer.append(2 * di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [10]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
xx = x * 2

In [14]:
xx

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
cc = np.array([4, 5, 6])

In [18]:
aa = np.array([1, 2, 3])

In [19]:
cc + aa

array([5, 7, 9])

In [21]:
dd = np.array([[1, 2, 3], [4, 5, 6]])

In [22]:
dd

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
aaa = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [32]:
aaa

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [33]:
aaa.dtype

dtype('int64')

In [34]:
aaa.shape

(2, 3, 3)

In [35]:
aaa.ndim

3

In [38]:
aaa[0, 2, 1]

8

In [40]:
b = np.array([1, 2, 4, 5, 6])

In [41]:
b

array([1, 2, 4, 5, 6])

In [42]:
b[0:2]

array([1, 2])

In [43]:
b[2:]

array([4, 5, 6])

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [44]:
a[0, 0:2]

array([1, 2])

In [47]:
for i in range(2, 10, 2):
    print(i)

2
4
6
8


In [48]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]])

In [49]:
a

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [50]:
for i in range(2):
    for j in range(5):
        if(j == 2 or j == 3):
            print(a[i, j])

3
4
8
9


In [52]:
for i in range(2):
    print(a[i, 2:4])

[3 4]
[8 9]


In [53]:
for i in range(2):
    for j in range(2, 4):
        print(a[i, j])

3
4
8
9


In [56]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [57]:
b = a[0:2, 2:4]

In [58]:
b

array([[3, 4],
       [7, 8]])

In [59]:
for i in range(2, 4):
    print(a[0, i-1])

2
3


In [60]:
for j in range(2):
    for i in range(2, 4):
        print(a[j, i])

3
4
7
8


In [62]:
b = np.array([])

In [63]:
for j in range(2):
    for i in range(2, 4):
        b.append(i)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [64]:
b = a[0, 2:4]

In [65]:
b

array([3, 4])

In [66]:
b = np.array([[], []])

In [67]:
b = a[0:2, 1:3]

In [68]:
b

array([[2, 3],
       [6, 7]])

In [70]:
a = np.array([0, 1, 0, 0])

In [74]:
b = np.array([1, 1, 0, 0])

In [75]:
c = a * b

In [76]:
c

array([0, 1, 0, 0])

In [77]:
np.sum(c)

1

In [108]:
block_L = np.array([
    [0, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 1, 1, 1],
    [0, 0, 0, 0]
])

In [91]:
background = np.array([
    [0, 1, 0, 0],
    [0, 1, 1, 1],
    [0, 0, 0, 0],
    [0, 0, 0, 0]
])

In [92]:
background.ndim

2

In [93]:
background.shape

(4, 4)

In [94]:
background.dtype

dtype('int64')

In [95]:
c = block_L * background

In [96]:
c = np.dot(block_L, background)

In [97]:
c

array([[0, 0, 0, 0],
       [0, 1, 1, 1],
       [0, 1, 1, 1],
       [0, 0, 0, 0]])

In [106]:
sum = 0
for i in range(4):
    if block_L[1, i] == 1 & background[1, i] == 1:
        sum += 1
sum

1

In [107]:
sum = 0
for j in range(4):
    for i in range(4):
        if block_L[j, i] == 1 & background[j, i] == 1:
            sum += 1
sum

2

In [104]:
block_L

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 1, 1],
       [0, 0, 0, 0]])

In [109]:
np.sum(block_L)

4