In [1]:
import numpy as np

In [2]:
a= np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [4]:
b = [[1, 2, 3, 4], [5, 6, 7,8]]

In [5]:
b

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [6]:
bbbb = a[0:2, 1:3]

In [7]:
a[0, 1]

2

In [8]:
a[0, 1:3]

array([2, 3])

In [15]:
aa = a[0:2, 1:3]

In [16]:
c = np.array([[1, 0], [0, 0]])

In [17]:
c

array([[1, 0],
       [0, 0]])

In [18]:
aa

array([[2, 3],
       [6, 7]])

In [19]:
aa * c

array([[2, 0],
       [0, 0]])

In [20]:
aa & c

array([[0, 0],
       [0, 0]], dtype=int32)